"""Leaves generator matched to vanilla's see-through canopy.

Vanilla oak/spruce/birch leaves are ~32-43% TRANSPARENT, with holes scattered
across the whole 16x16 (not just edges) — that lacy read is what says "leaves".
Our first leaves were ~8% holes and read as a solid green cube. This rebuilds
both woods from ONE shared structure (tileable clumped value field + a ~34%
hole mask, both wrapped) recolored per wood — the one-arrangement-many-palettes
rule. Leaves are the sanctioned place for high-frequency holes.

Run from the Pixel-Art-Aide repo root:
    python3 gallery/2026-07-19-tna-texture-pass/src/make_leaves.py
"""

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from aide.grid import Pxg, parse_color, save_texture, to_image, to_text

SESSION = Path(__file__).resolve().parents[1]
N = 16
HOLE_FRACTION = 0.34  # matches vanilla (~32-43%)

LEAVES = {
    "greatwood_leaves": {
        # deep, shadow, base, light, highlight
        "ramp": ["1F3A1E", "2E5023", "3E6B2F", "4E8039", "5C9440"],
        "glint": None,
    },
    "silverwood_leaves": {
        "ramp": ["6F9E94", "8BBFAC", "A9D8C4", "C0E8D6", "D5F2E6"],
        "glint": "7FE8D8",  # sparse teal shimmer (card magic accent)
    },
}


def wrapped_value_field(rng, passes=2):
    """A smooth-ish tileable value field in [0,1) via wrapped neighbour blur."""
    f = [[rng.random() for _ in range(N)] for _ in range(N)]
    for _ in range(passes):
        g = [[0.0] * N for _ in range(N)]
        for y in range(N):
            for x in range(N):
                s = 0.0
                for dy in (-1, 0, 1):
                    for dx in (-1, 0, 1):
                        s += f[(y + dy) % N][(x + dx) % N]
                g[y][x] = s / 9
        f = g
    return f


def hole_mask(rng):
    """~HOLE_FRACTION cells True (=hole), SCATTERED high-frequency like vanilla
    (per-cell, not blob-clustered). No large contiguous gaps."""
    holes = set()
    for y in range(N):
        for x in range(N):
            if rng.random() < HOLE_FRACTION:
                holes.add((x, y))
    # break up any accidental 2x2 fully-transparent block (keeps it lacy, not holey)
    for y in range(N):
        for x in range(N):
            quad = [(x, y), ((x + 1) % N, y), (x, (y + 1) % N), ((x + 1) % N, (y + 1) % N)]
            if all(c in holes for c in quad):
                holes.discard(quad[rng.randint(0, 3)])
    return holes


def build(name, spec):
    rng = random.Random(20 if "great" in name else 21)  # distinct but stable per wood
    val = wrapped_value_field(random.Random(7), passes=2)  # SHARED value structure
    holes = hole_mask(random.Random(11))                   # SHARED hole layout
    ramp = spec["ramp"]

    keys = "Dsblh"  # 5 ramp steps
    palette = {".": (0, 0, 0, 0)}
    for k, hexv in zip(keys, ramp):
        palette[k] = parse_color(hexv)
    if spec["glint"]:
        palette["g"] = parse_color(spec["glint"])

    rows = []
    glint_budget = 3 if spec["glint"] else 0
    for y in range(N):
        row = []
        for x in range(N):
            if (x, y) in holes:
                row.append(".")
                continue
            step = min(4, int(val[y][x] * 5.999))
            # sparse glint on the lightest cells, silverwood only
            if glint_budget and step >= 3 and rng.random() < 0.06:
                row.append("g")
                glint_budget -= 1
            else:
                row.append(keys[step])
        rows.append("".join(row))

    pxg = Pxg(width=N, height=N, palette=palette, rows=rows)
    (SESSION / "src" / f"{name}.pxg").write_text(
        f"# {name} — generated by make_leaves.py (vanilla ~34% holes); edit the script\n"
        + to_text(pxg))
    save_texture(to_image(pxg), SESSION / "out" / f"{name}.png")
    opaque = sum(r.count(c) for r in rows for c in "Dsblhg")
    print(f"{name}: {N*N - opaque} holes ({100*(N*N-opaque)//(N*N)}% transparent)")


def main():
    for name, spec in LEAVES.items():
        build(name, spec)


if __name__ == "__main__":
    main()
