"""Gilded planks (4 wood x metal pairings) + arcane worktable faces.

Builds on make_wood's plank arrangement (same seed -> identical grid, per
the one-arrangement-many-palettes lesson). Gilding follows art-direction:
thin metal inlay banding, 1px lines with sparse joints/glints — never full
metal borders. Aetherium bands always carry exactly one teal glint per
band; brass never glints.

Run from the Pixel-Art-Aide repo root:
    python3 gallery/2026-07-19-tna-texture-pass/src/make_gilded.py
"""

import random
import sys
import zlib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from aide.grid import Pxg, parse_color, to_image, to_text
from make_wood import PLANKS, gen_planks  # noqa: E402  (same dir import)

SESSION = Path(__file__).resolve().parents[1]
KEYS = "abcdefghijklmnop"

METALS = {
    "brass": ["8F6B38", "C79A55", "E8C983"],          # shadow, base, highlight
    "aetherium": ["5A4380", "8A6BB5", "B99BE0", "7FE8D8"],  # + glint
}

GILDED = {
    "gilded_greatwood_brass": ("greatwood_planks", "brass"),
    "gilded_silverwood_aetherium": ("silverwood_planks", "aetherium"),
    "gilded_greatwood_aetherium": ("greatwood_planks", "aetherium"),
    "gilded_silverwood_brass": ("silverwood_planks", "brass"),
}

BAND_ROWS = (3, 11)  # two of the four seam rows carry the inlay


def band(rng, metal: str) -> list[int]:
    """One 16px inlay line: metal base with joints and sparse highlights."""
    row = []
    for x in range(16):
        if x % rng.choice([5, 6]) == 4:
            row.append(8)  # joint (metal shadow)
        elif rng.random() < 0.15:
            row.append(10)  # highlight
        else:
            row.append(9)  # base
    if metal == "aetherium":
        row[rng.randrange(16)] = 11  # exactly one glint per band
    return row


def emit(name: str, grid: list[list[int]], tones: list[str], note: str) -> None:
    palette = {KEYS[i]: parse_color(t) for i, t in enumerate(tones)}
    rows = ["".join(KEYS[t] for t in row) for row in grid]
    pxg = Pxg(width=16, height=16, palette=palette, rows=rows)
    (SESSION / "src" / f"{name}.pxg").write_text(f"# {name} — generated by make_gilded.py ({note})\n" + to_text(pxg))
    to_image(pxg).save(SESSION / "out" / f"{name}.png")
    print(name)


def main() -> None:
    base = gen_planks(random.Random(41))  # same arrangement as make_wood
    for name, (wood, metal) in GILDED.items():
        rng = random.Random(zlib.crc32(name.encode()))  # stable across runs (hash() is salted)
        grid = [list(r) for r in base]
        for y in BAND_ROWS:
            grid[y] = band(rng, metal)
        tones = PLANKS[wood]["wood"] + PLANKS[wood]["seam"] + METALS[metal]
        emit(name, grid, tones, f"{wood} + {metal} inlay banding")

    # Arcane worktable: greatwood furniture with a brass working band.
    gw = PLANKS["greatwood_planks"]
    tones = gw["wood"] + gw["seam"] + METALS["brass"] + ["7FE8D8", "8A6BB5"]
    # indices: wood 0-4, seam 5-7, brass 8-10, glint 11, aetherium 12

    top = [list(r) for r in base]
    for cx, cy in [(0, 0), (14, 0), (0, 14), (14, 14)]:  # brass corner caps
        for dx in range(2):
            for dy in range(2):
                top[cy + dy][cx + dx] = 10 if (dx == 0 and dy == 0) else (8 if dx + dy == 2 else 9)
    for x, y, t in [(7, 7, 12), (8, 7, 12), (7, 8, 12), (8, 8, 11)]:  # inlaid focus socket
        top[y][x] = t
    emit("arcane_worktable_top", top, tones, "plank surface, brass caps, aetherium socket")

    rng = random.Random(9)
    side = [list(r) for r in base]
    side[1] = band(rng, "brass")  # working band under the tabletop edge
    for y in range(16):  # corner posts read darker
        for x in (0, 15):
            side[y][x] = max(0, side[y][x] - 2) if side[y][x] <= 4 else side[y][x]
    emit("arcane_worktable_side", side, tones, "planks, brass band, dark posts")

    bottom = [[max(0, t - 1) if t <= 4 else t for t in row] for row in base]
    emit("arcane_worktable_bottom", bottom, tones, "darkened planks")


if __name__ == "__main__":
    main()
