"""Vanilla-idiom plank and log-side generator for both T.N.A. woods.

Derived from studying real 1.21.1 planks/logs (user-linked refs):
- planks: 4 boards x 4 rows; NO vertical joints; wood rows are runs (1-5px)
  of 4-5 CLOSE tones (top row biased light, third row biased dark); seam
  rows are broken mixes of three dark tones, never a uniform line.
- logs: vertical strips with per-column tone bias, runs 1-4 tall, ~6 close
  bark tones; silverwood additionally gets sparse dark streak dashes.
- vanilla reuses ONE arrangement across woods (spruce/birch planks share a
  grid) — we do the same: one generated arrangement, two palettes. The
  arrangement itself is ours (seeded), never transcribed from vanilla.

Run from the Pixel-Art-Aide repo root:
    python3 gallery/2026-07-19-tna-texture-pass/src/make_wood.py
"""

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from aide.grid import Pxg, parse_color, save_texture, to_image, to_text

SESSION = Path(__file__).resolve().parents[1]

# tone roles: planks wood [dark, mid-dark, base, mid-light, light], seams x3
PLANKS = {
    "greatwood_planks": {
        "wood": ["3E2C1F", "47341F", "4F3B25", "58432A", "60492C"],
        "seam": ["2A1C16", "30201C", "382A20"],
    },
    "silverwood_planks": {
        "wood": ["A8AC9D", "BCC0B0", "CFD3C4", "D9DCCE", "E4E7DA"],
        "seam": ["818B85", "8A948E", "96A098"],
    },
}
LOGS = {
    "greatwood_log": {
        "bark": ["332720", "3A2D22", "44352A", "4E3D2E", "56443A", "5E4A38"],
        "dash": None,
    },
    "silverwood_log": {
        "bark": ["C2C8C2", "D0D5D0", "D9DED9", "E0E4E0", "E8ECE8", "AAB2AC"],
        "dash": "8E9691",
    },
}

KEYS = "abcdefghij"


def runs(rng, n, weights):
    """A row of n tone-indices as random-length runs (vanilla grain)."""
    row = []
    while len(row) < n:
        tone = rng.choices(range(len(weights)), weights=weights)[0]
        row.extend([tone] * rng.randint(1, 5))
    return row[:n]


def gen_planks(rng) -> list[list[int]]:
    """Tone-index grid: wood indices 0-4, seam indices 5-7."""
    grid = []
    for _ in range(4):  # boards
        grid.append(runs(rng, 16, [1, 2, 4, 3, 3]))  # top row: lighter bias
        grid.append(runs(rng, 16, [2, 3, 4, 2, 1]))
        grid.append(runs(rng, 16, [3, 4, 3, 2, 1]))  # lower row: darker bias
        grid.append([5 + t for t in runs(rng, 16, [3, 4, 3])])  # seam row
    return grid


def gen_log(rng, dash: bool) -> list[list[int]]:
    """Tone-index grid via vertical runs; index 6 marks a dash streak.

    Dash-woods (birch idiom) get a CALM field — mostly the mid-pale tones —
    so the defined dark dashes carry the character, per the vanilla birch
    reference. Dark woods get fuller strip variation, per spruce.
    """
    if dash:
        biases = [[1, 2, 5, 5, 2, 1], [0, 2, 6, 4, 2, 1], [1, 3, 5, 4, 2, 0]]
    else:
        biases = [[4, 3, 2, 1, 1, 1], [1, 2, 3, 4, 2, 1], [1, 1, 2, 3, 4, 2]]
    cols = []
    for x in range(16):
        bias = rng.choice(biases)
        col, y = [], 0
        while y < 16:
            tone = rng.choices(range(6), weights=bias)[0]
            for _ in range(rng.randint(1, 4)):
                if y < 16:
                    col.append(tone)
                    y += 1
        cols.append(col)
    grid = [[cols[x][y] for x in range(16)] for y in range(16)]
    if dash:
        for _ in range(8):  # defined streak dashes, some 2px tall (birch idiom)
            x, y = rng.randint(0, 13), rng.randint(0, 14)
            w = rng.randint(2, 3)
            for i in range(w):
                grid[y][x + i] = 6
            if rng.random() < 0.35:
                for i in range(w):
                    grid[y + 1][x + i] = 6
    return grid


def emit(name: str, tone_grid: list[list[int]], tones: list[str], note: str) -> None:
    palette = {KEYS[i]: parse_color(t) for i, t in enumerate(tones)}
    rows = ["".join(KEYS[t] for t in row) for row in tone_grid]
    pxg = Pxg(width=16, height=16, palette=palette, rows=rows)
    text = f"# {name} — generated by make_wood.py ({note}); edit the script, not this file\n" + to_text(pxg)
    (SESSION / "src" / f"{name}.pxg").write_text(text)
    save_texture(to_image(pxg), SESSION / "out" / f"{name}.png")
    print(name)


def main() -> None:
    rng = random.Random(41)
    plank_grid = gen_planks(rng)  # ONE arrangement, both palettes (vanilla-style)
    for name, p in PLANKS.items():
        emit(name, plank_grid, p["wood"] + p["seam"], "vanilla-idiom planks, shared arrangement")
    for name, l in LOGS.items():
        grid = gen_log(random.Random(7 if l["dash"] else 5), bool(l["dash"]))
        tones = l["bark"] + ([l["dash"]] if l["dash"] else [])
        emit(name, grid, tones, "vanilla-idiom bark")


if __name__ == "__main__":
    main()
